### ISSUE TITLE
would that be an error?

### ISSUE THREAD

**Issue by GrInDmEtAl** [Azexios/openwrt-r3p-mtk#1]
[ 1269.425291] Show_MacTable_Proc(): arg=
[ 1269.429135] Dump MacTable entries info, EntType=0x20001
========
[ 1634.013811] dev_rx_ctrl_frm(): Cannot found WCID of BAR packet!
[ 1634.019839] dev_rx_ctrl_frm(): Cannot found WCID of BAR packet!

===

Wed May 11 03:22:25 2022 daemon.err uhttpd[1019]: cat: can't open '/tmp/mtk/ifup-save': No such file or directory

=======other tmp errorWed May 11 03:22:56 2022 daemon.err uhttpd[1019]:
Wed May 11 03:22:57 2022 daemon.err uhttpd[1019]: rai0      No such device
Wed May 11 03:22:57 2022 daemon.err uhttpd[1019]:
Wed May 11 03:22:58 2022 daemon.err uhttpd[1019]: rai0      No such device
Wed May 11 03:22:58 2022 daemon.err uhttpd[1019]:
Wed May 11 03:23:15 2022 daemon.err uhttpd[1019]: rai0      no private ioctls.
Wed May 11 03:23:15 2022 daemon.err uhttpd[1019]:
Wed May 11 03:23:17 2022 daemon.err uhttpd[1019]: rai0      no private ioctls.
Wed May 11 03:23:17 2022 daemon.err uhttpd[1019]:
Wed May 11 03:23:18 2022 daemon.err uhttpd[1019]: rai0      No such device
Wed May 11 03:23:18 2022 daemon.err uhttpd[1019]:
Wed May 11 03:23:18 2022 daemon.err uhttpd[1019]: rai0      No such device
Wed May 11 03:23:18 2022 daemon.err uhttpd[1019]:
Wed May 11 03:23:19 2022 daemon.err uhttpd[1019]: rai0      no private ioctls.
Wed May 11 03:23:19 2022 daemon.err uhttpd[1019]:
Wed May 11 03:23:20 2022 daemon.err uhttpd[1019]: rai0      No such device
Wed May 11 03:23:20 2022 daemon.err uhttpd[1019]:
Wed May 11 03:23:20 2022 daemon.err uhttpd[1019]: rai0      No such device

**Comment by Azexios** [comment]
It may no longer be relevant, but

_>dev_rx_ctrl_frm(): Cannot found WCID of BAR packet!_
I don't know, I don't have anything like that in my logs.

_>cat: can't open '/tmp/mtk/ifup-save': No such file or directory_
It doesn't affect anything (the error doesn't appear in the latest update).

_>rai0 No such device_
No rai0 = No 5GHz

If you have R3P, then compare my "config.buildinfo" (https://github.com/Azexios/openwrt-r3p-mtk/releases/tag/21.02.3_up) with yours.

**Comment by GrInDmEtAl** [comment]
I managed to fix it, it was a problem in generating the image, and settings with MAC it was all in FF FF FF , because of Keenetic I used it before and it ended up generating these Logs as seen above due to the lack of EEPROM.bin and a warning for people who use Keenetic have eeprom Backup because it removes the original calibrations of the r3p router, restoring the eeprom.bin problem was solved
