### ISSUE TITLE
Is it support for newifi d2?

### ISSUE THREAD

**Issue by malikshi** [Azexios/openwrt-r3p-mtk#2]
I saw this post on newifi d2 thread https://4pda.to/forum/index.php?showtopic=957085&view=findpost&p=115855746

**Comment by Azexios** [comment]
Yes, it supports.

**Comment by malikshi** [comment]
I want to install op 22/snapshot.
Are these https://github.com/Azexios/openwrt-r3p-mtk/blob/main/README_RU.md guides updated? I'm using google translate to EN since no EN guides

**Comment by Azexios** [comment]
The guide is relevant, but on version 22.03, the build for 7603+7612 has not yet been tested.

**Comment by malikshi** [comment]
> The guide is relevant, but on version 22.03, the build for 7603+7612 has not yet been tested.

what's your recommendation for newifi d2 between immortalwrt and official openwrt?

**Comment by Azexios** [comment]
I don't have devices with mt7603+mt7612 - so I can't definitely say which is better.
immortalwrt as far as I know does not support openwrt 22.03

Try the official openwrt first, maybe you will be satisfied with the work of their mt76 driver.

**Comment by malikshi** [comment]
> Try the official openwrt first, maybe you will be satisfied with the work of their mt76 driver.

the 5G speed around 80-120Mbps, with eeprom update can get 200Mbps

**Comment by Azexios** [comment]
> the 5G speed around 80-120Mbps, with eeprom update can get 200Mbps

And what was the speed on the stock firmware?

It is best to simply install the firmware using your link (OpenWRT 21.02.3+MTK.zip):
> I saw this post on newifi d2 thread https://4pda.to/forum/index.php?showtopic=957085&view=findpost&p=115855746

and compare the speed with the official openwrt.

**Comment by malikshi** [comment]
> > the 5G speed around 80-120Mbps, with eeprom update can get 200Mbps
> 
> And what was the speed on the stock firmware?
> 
> It is best to simply install the firmware using your link (OpenWRT 21.02.3+MTK.zip):
> 
> > I saw this post on newifi d2 thread https://4pda.to/forum/index.php?showtopic=957085&view=findpost&p=115855746
> 
> and compare the speed with the official openwrt.

i can;t downloads the files. can you send it there?

**Comment by malikshi** [comment]
can you help to sent the files or build for newifi d2?
i got error while trying to build them
```
make[5]: *** [Makefile:2345: s-automata] Error 137
make[4]: *** [Makefile:4251: all-gcc] Error 2
make[3]: *** [Makefile:37: /home/malik/openwrt-21.02.3/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/.built] Error 2
make[2]: *** [toolchain/Makefile:97: toolchain/gcc/initial/compile] Error 1
make[1]: *** [toolchain/Makefile:93: /home/malik/openwrt-21.02.3/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/stamp/.toolchain_compile] Error 2
make: *** [/home/malik/openwrt-21.02.3/include/toplevel.mk:230: world] Error 2
```

**Comment by Azexios** [comment]
>i can;t downloads the files. can you send it there?

I downloaded this file:
[OpenWRT+21.02.3+MTK.zip](https://github.com/Azexios/openwrt-r3p-mtk/files/9034945/OpenWRT%2B21.02.3%2BMTK.zip)
.

**Comment by malikshi** [comment]
> > i can;t downloads the files. can you send it there?
> 
> I downloaded this file: [OpenWRT+21.02.3+MTK.zip](https://github.com/Azexios/openwrt-r3p-mtk/files/9034945/OpenWRT%2B21.02.3%2BMTK.zip) .

thank you. i will try it after one of my vps done compiling i hope no errors. i running 2 vps to compile. one of them still on progress another one was error

**Comment by malikshi** [comment]
after do some iperf3, [OpenWRT+21.02.3+MTK.zip](https://github.com/Azexios/openwrt-r3p-mtk/files/9034945/OpenWRT%2B21.02.3%2BMTK.zip) 
wifi 4 90Mbps
wifi 5 150Mbps
i tried between 40 and 80Mhz.

i have bit problems when i set 2 ssid with same config(wifi4 + wifi5), my phone keep connected to wifi 4 normally it's should connected to wifi5 then wifi4 if the range too far.
is it support fast transition?

**Comment by Azexios** [comment]
I do not know what this is related to, but as a rule, to influence the client's choice of a range (2,4 or 5), support for "Band Steering" is required - it is not implemented here.

**Comment by malikshi** [comment]
Just finished setup with official OpenWrt SNAPSHOT, r20011-265f402fbd
Speed wifi 5 with 40Mhz are between 140-270Mbps with avg 190Mbps. The problems are the band options are limited. I think i gonna stick with official one without your mtk porting
