### ISSUE TITLE
[Нужна помощь] Ошибка при сборке модуля ядра mt7615d

### ISSUE THREAD

**Issue by 9uyone** [Azexios/openwrt-r3p-mtk#3]
Не знаю, как решить, поэтому прошу помощи.

`ERROR: modpost: "Set_Enable_Dpp_Proc" [/home/guy0n3/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7615d/mt_wifi_ap/mt_wifi.ko] undefined!
ERROR: modpost: "ppe_dev_unregister_hook" [/home/guy0n3/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7615d/mt_wifi_ap/mt_wifi.ko] undefined!
ERROR: modpost: "ppe_dev_register_hook" [/home/guy0n3/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7615d/mt_wifi_ap/mt_wifi.ko] undefined!
ERROR: modpost: "ra_sw_nat_hook_tx" [/home/guy0n3/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7615d/mt_wifi_ap/mt_wifi.ko] undefined!
ERROR: modpost: "ra_sw_nat_hook_rx" [/home/guy0n3/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7615d/mt_wifi_ap/mt_wifi.ko] undefined!
make[5]: *** [scripts/Makefile.modpost:124: /home/guy0n3/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7615d/mt_wifi_ap/Module.symvers] Error 1
make[5]: *** Deleting file '/home/guy0n3/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7615d/mt_wifi_ap/Module.symvers'
make[4]: *** [Makefile:1726: modules] Error 2
make[4]: Leaving directory '/home/guy0n3/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.10.131'
make[3]: *** [Makefile:218: /home/guy0n3/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7615d/.built] Error 2
make[3]: Leaving directory '/home/guy0n3/openwrt/package/mt/drivers/mt7615d'
time: package/mt/drivers/mt7615d/compile#3.74#0.64#4.49
ERROR: package/mt/drivers/mt7615d failed to build.`

**Comment by Azexios** [comment]
Используйте дефолтные настройки драйвера (судя по логу - Вы их изменили).
Изменять параметры стоит только, если Вы понимаете за что они отвечают и готовы сами исправлять возможные ошибки.

**Comment by 9uyone** [comment]
Да, с дефолтными настройками собралось. Буду знать, что если и экспериментировать с ними, то с осторожностью и записывать все изменения.
