### ISSUE TITLE
Предложение: добавить в конфиг больше параметров Fast Transition

### ISSUE THREAD

**Issue by 9uyone** [Azexios/openwrt-r3p-mtk#4]
Кроме самых основных параметров, которые есть в конфиге (FtSupport, FtMdId, FtOtd, FtRic) хотелось бы иметь и другие: идентификатор NAS/R0KH-ID, крайний срок реассоциации, генерировать PMK локально, проталкивание PMK R1, продолжительность жизни ключа R0, владелец ключа R1, внешний список владельцев ключей R0 и R1. Было б ещё хорошо, если б это было вынесено ещё как отдельные параметры на странице.

Можно было б использовать 802.11s Mesh, но, как я понимаю, в этом драйвере нет поддержки данного стандарта.

**Comment by Azexios** [comment]
По роумингу: я не могу это реализовать - у меня только один роутер на mtk а все параметры нужно проверять-тестировать + нужно написать демон/приложение для обмена информации между точками доступа. Да и особого желания тратить на это время у меня нет (мой роутер покрывает всю квартиру).

По Mesh: это в первую очередь поддержка со стороны прошивки, а не драйвера, а поддержки в OpenWrt для mtk по понятным причинам нет.
По сути для полноценной реализации функционала нужно делать свою сборку OpenWrt, но тратить огромное количество времени на проприетарный драйвер (который случайно или нет слили в сеть) такое себе занятие.
