### ISSUE TITLE
not an issues just some help

### ISSUE THREAD

**Issue by bricco1981** [Azexios/openwrt-r3p-mtk#5]
hi, can you please add mt7622+mt7915 or help me to do that please? I am referring to your beautiful integration in luci

**Comment by Azexios** [comment]
Hi,
I no longer plan to add other Wi-Fi chipsets. Only minor fixes/improvements and support for the latest up-to-date version of OpenWrt.
Perhaps if I buy a router with mt7915 in the future, I will add support for this chipset.

**Comment by bricco1981** [comment]
hi,
 i have one, xiaomi ax3200, and i have a netgear r6260 that's why i asked, because i have that on r6260 and that's great
