### ISSUE TITLE
ERROR: modpost: "wireless_send_event" target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/mt7603e.ko] undefined!

### ISSUE THREAD

**Issue by TurboBlaze** [Azexios/openwrt-r3p-mtk#6]
Hi.
I tried to compile OpenWRT current with MTK drivers and stuck on this error:
/home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/../mt7603_wifi/ate/qa_agent.o /home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/../mt7603_wifi/ate/mt_mac/mt_ate.o;  echo; } > /home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/mt7603e.mod
  {   echo /home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/mt7603e.ko; :; } | awk '!x[$0]++' - > /home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/modules.order
`make -f ./scripts/Makefile.modpost
  sed 's/ko$/o/' /home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/modules.order | scripts/mod/modpost     -o /home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/Module.symvers -e -i Module.symvers   -T -
ERROR: modpost: "wireless_send_event" [/home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/mt7603e.ko] undefined!`
make[5]: *** [scripts/Makefile.modpost:123: /home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/Module.symvers] Error 1
make[5]: *** Deleting file '/home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/mt7603_wifi_ap/Module.symvers'
make[4]: *** [Makefile:1736: modules] Error 2
make[4]: Leaving directory '/home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.10.144'
make[3]: *** [Makefile:139: /home/blaze/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mt7603_wifi/.built] Error 2
make[3]: Leaving directory '/home/blaze/openwrt/package/mt/drivers/mt7603e'
time: package/mt/drivers/mt7603e/compile#95.90#7.44#104.87
    ERROR: package/mt/drivers/mt7603e failed to build.
make[2]: *** [package/Makefile:116: package/mt/drivers/mt7603e/compile] Error 1
make[2]: Leaving directory '/home/blaze/openwrt'
make[1]: *** [package/Makefile:110: /home/blaze/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/blaze/openwrt'
make: *** [/home/blaze/openwrt/include/toplevel.mk:231: world] Ошибка 2
[blaze@blaze-VirtualBox](mailto:blaze@blaze-VirtualBox):~/openwrt$

Anybody knows how to fix it?

Thanks.

**Comment by Azexios** [comment]
Hi, 
Maybe it's the parameters, throw off the ".config" with which you are collecting, I'll see how the time will be.

--
>  make: *** [/home/blaze/openwrt/include/toplevel.mk:231: world] **Ошибка 2**

Можно писать по русски (если знаете русский).

**Comment by TurboBlaze** [comment]
Здравствуйте.
Хорошо =)
Я пытаюсь собрать прошивку с проприетарными драйверами для Билайн Smart Box Turbo+ (ramips mt7621 - https://openwrt.org/inbox/toh/beeline/smartbox_turbo_plus)
Мой .config такой https://pastebin.com/E1Uq45gP
Спасибо!

**Comment by Azexios** [comment]
Я попробовал собрать прошивку на ветке мастер и получил туже ошибку. Также попробовал собрать для Redmi AC2100 -  аналогичная ошибка, при этом 22.03.0 для Redmi AC2100 собирается без проблем.
У меня нет времени на поддержку мастер ветки (она обновляется каждый день). Могу лишь посоветовать попробовать добавить smartbox turbo в стабильную 22.03.0

**Comment by Azexios** [comment]
И кстати, у Вас в конфиге выбран Smart Box Turbo без "+", я не знаю насколько это критично, на всякий случай написал )

**Comment by TurboBlaze** [comment]
Спасибо за предоставленную информацию!
Буду искать решение. Если найду сообщу.
